// components/hero/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import logo from "../public/logo.png";
import { serverClient, ActionOutput } from "oc-server";
const props = defineProps<{
  firstName: string;
  lastName: string;
  born: number;
  hobbies: string[];
}>();

const additionalData = ref<ActionOutput<"funFact"> | null>(null);
async function getFunFact() {
  additionalData.value = await serverClient.funFact({ year: props.born });
}
const hobbies = props.hobbies.map((x) => x.toLowerCase()).join(", ");
</script>

<template>
  <div className="container">
    <img width="50" height="50" v-bind:src="logo" alt="Logo" />

    <h1>This section is in Vue Js</h1>
  </div>
</template>

<style scoped>
.container {
  background-color: #ffa500;
  color: #fff;
  font-family: sans-serif;
  padding: 40px;
  text-align: center;
}

.button {
  background-color: #a97613;
  border: none;
  padding: 15px 32px;
  text-align: center;
  font-size: 16px;
  text-decoration: none;
  display: inline-block;
  color: inherit;
  cursor: pointer;
}

h1 {
  margin: 0 0 20px 0;
}

span {
  text-decoration: underline;
}

.info {
  margin-bottom: 20px;
}

.block {
  margin: 6px 0;
}
</style>

// components/header/src/App.tsx
import { useState } from 'react';
import { serverClient, InitialData, ActionOutput } from 'oc-server';
import styles from './styles.css';
import logo from '../public/logo.png';

type AdditionalData = ActionOutput<'funFact'>;

const App: React.FC<InitialData> = (props: InitialData) => {
  const { firstName, lastName, born, hobbies } = props;
  const [additionalData, setAdditionalData] = useState<AdditionalData | null>(
    null
  );
  const [error, setError] = useState('');

  const getFunFact = async () => {
    setError('');
    try {
      const data = await serverClient.funFact({ year: born });
      setAdditionalData(data);
    } catch (err) {
      setError(String(err));
    }
  };

  if (error) {
    return <div>Something wrong happened!</div>;
  }

  return (
    <div className={styles.container}>
      <img width="50" height="50" src={logo} alt="Logo" />
      <h1 style={{ margin: '0 0 20px 0' }}>
        This header is a react component
      </h1>
    </div >

  );
};

export default App;
